* スクラムマスターは何をするのか

これまで私は、スクラムマスターとはあまり縁のない仕事をしてきた。
スクラムをやるようになって最初の数年はスクラムマスターは兼任者のみだった。
彼はリーダー、あるいは司会者といった役割に徹していた。
その後転職して2年ほどはスクラムマスター無し。
今では専任のスクラムマスターが採用され、チームに参加している。
しかし、スクラムマスターがいても、いなくても、自分の仕事にはほとんど変化がないように感じる。

プログラマならプログラムを書く。デザイナーならデザインを作る。
プロダクトオーナーは製品のあるべき仕様を決める。
では、スクラムマスターは何をするのだろうか。

* スクラムマスターはマネージャーなのか

スクラムマスターがチームに貢献している点を想像してみる。
現在では、計画作り、進捗管理に大きく時間を割いているようだ。
これはマネージャーの仕事に近い。

進捗管理は、一人の開発者からみるとさほど重要ではない。
なぜなら、日々作業している自分が、進捗を一番理解しているからだ。
遅れているにしても、その原因は誰かが怠けているわけではない。
止むを得ない。ゴールに間に合わせることよりもまず、延期できないか。
そういう考え方をする。

一方、プロダクトオーナーからすると進捗管理は重要だ。
少しでも遅れる可能性があるなら、素早くそれを察知して計画を立て直したい。
ライバルに先んじて機能をリリースすることは重要だ。

プロダクトオーナーと開発者が対話することでバランスを取ることはできる。
しかし客観的にバランスを取るメンバーがいるほうが話を進めやすい。
そういうわけでスクラムマスターはいたほうが良いのだろうか。
それはマネージャーとは違うのだろうか。

* スクラムマスターに期待していたこと

かつてのスクラムマスターがそうだったように、
私は現在のスクラムマスターにもプロジェクトリーダーとしての振る舞いを期待していた。
何が重要なのかを知っていて、問題の聞き手となり、解決のための案を出せる人であってほしい。
そう考えていた。
しかし、入社して1年とたたないスクラムマスターにそれを期待するのは酷である。
圧倒的にドメイン知識、技術的な知識が不足している。
問題の聞き手になることはできても、適切な判断を下し、チームを導くことは困難だ。
だから今は、コーチであることを期待するのが良いのではないかと想像した。

* スクラムマスターはプロセスの先導者であり守護者

スクラムマスターについて解説しているいくつかの記事を眺めた。

https://asana.com/ja/resources/scrum-master
https://www.atlassian.com/ja/agile/scrum/scrum-master

スクラムマスターは、プロセスの先導者であり守護者なのだとわかった。
スクラムマスターは、スクラムという枠の中で力を発揮する。
チームがスクラムにそって成長し、生産性をあげていくように働きかける。

ここで、一つ気づいたことがある。私は、スクラムを「やりたい」と思っていない。
さらに言えば、スクラムマスターをチームの「先導者」と考えていない。
スクラムマスターが機能していないように感じるのは、まさにそこが原因だ。
私は無意識にスクラムに逆らって、自分のやりたいように仕事をしようとしている。
だからスクラムマスターが力を発揮できないのだと思う。

* なぜ型通りのスクラムを嫌がるのか

デイリースクラムに始まり、スプリントプランニング、
スプリントレビュー、レトロスペクティブなどのイベントは理にかなっていると思う。
全てのタスクに見積もりを出して、計画を立て、バーンダウンチャートを描くのもよい。

だが、スクラムのプロジェクト管理に zenhub を使っているのがうまくいっていない。
zenhub は github の issue に階層構造を持たせて管理するという考え方を持っている。
しかし、それにより情報の分散が起きている。必要のない階層構造を持つことで、
issue に取り組む上で必要な情報が issue に記載されていない。
別の設計資料にまとめて管理されている。これがわかりにくさに繋がっている。
加えて、zenhub 自体のパフォーマンスが非常に悪く、操作が重い。
そのために、バーンダウンチャートや、プランニングポーカーといった便利な昨日の快適さを損なっている。
毎日みるはずのカンバンは重たすぎて見る気にもならない。
自分のタスクだけ github で確認している。
改めて私は zenhub を使いこなせていないと思う。
zenhub を積極的に使おうという心意気や経験が足りてないのだと思う。
チームの中でどのように使っていくのかというルールも曖昧なままだ。
その点を整理しないままにプロジェクトを進めているのはよくなかった。

こういう点を整備しつつ、スクラムは楽しいよ、効率的だよという認知をしなければならない。
そこでの合意がとれれば、スクラムマスターがやろうとしていることに寄り添っていけるような気がする。
