* 1

僕は、心を無にして体を動かしていた。作業服を着て、なんだかよくわからない荷物を運ぶだけの仕事だ。つまらない仕事だけれど、実入りは悪くない。何より、脳を使わずにお金を稼ぐことができる。どれだけ体がきしんだところで、心は傷まないから、安らかなままでいられる。それくらいが身の丈にあっている。

大手通販サイトが管理するこの巨大倉庫の中では、自分がミニチュア模型みたいに、ちっぽけな存在だということがわかる。すれ違う男たちは、帽子をかぶって目を合わさないようにしている。酸素を運ぶヘモグロビンのように、休むことなく働き続けている。僕らは、巨大なシステムに組み込まれたささやかな部品にすぎないのだ。高度な機械化が進んだ今でも、人間が酷使されているのは、僕らがあまりにも安いからだろう。そして僕たちは、それを受け入れねばならないほど、明らかに貧しい。

生きていくための仕事が終わって、崩れ落ちるようにアパートの床に転がった。帰りがけに買ったランチパックをかじりながら、家計簿アプリを見る。残る借金が一億七百二十八万と少し。絶望的に遠い金額だ。それでも、少しずつ少しずつ右肩下がりに減っている。生涯をかけて、返済することになるのだろうか。

三年前の事件を思い出す。あの頃の僕はもっとやる気がなくて、けれど悩みはなく、もっと生きている顔をしていたと思う。大学のつてで、家庭教師のアルバイトをしていた。人と関わりを持つことに関しては嫌いではなかったし、それなりに教えるのは得意だった。実際それまでに教えてきた生徒たちは、満足のいく成果を出していた。

その実績を認められて、とある家庭に招かれた。そうして出会った少年は、これまでにない事情を抱えていた。数年前から、重い病気を患い、半身が麻痺しているのだという。言葉を話すことができず、表情を作ることができなかった。ただ、左手の人差し指だけは負担なく動かすことができたので、わずかなフリック動作で文字を入力する専用の機械を作って、どうにかコミュニケーションを取っているらしい。

初めて対面した時、彼は唐突な依頼を持ちかけてきた。彼の腕に繋がっている点滴の輸液に十グラムの食塩を混ぜてほしい、と。明らかな自殺行為だった。彼の境遇を思うと、やむを得ないことなのかもしれない。自暴自棄にならないでほしい。僕はそう断った。彼は社会的弱者として、さんざん憐れみを受けて生きてきたのだろうと想像した。だから、僕は逆に、対等な人間として扱うべきだと考えた。

教えた科目は数学だった。数式を見せて、その意味を説明することはできたが、彼はなかなか問題を解くことができなかった。彼のために作られた機械は数式入力に対応していなかったせいだろう。そう考えて、彼の両親に依頼して、微分積分やら、漸化式や行列といった数式を書き出せるようにアップグレードをしてもらった。決して安い金額ではなかったようだが、彼の両親は惜しみなく資財を投じた。

家庭のサポートと彼自身の努力にもかかわらず、成果は芳しくなかった。僕は報酬のない残業をして彼の成績を伸ばそうとしたが、うまくいかなかった。原因がなんなのか、わからなかった。教え方が悪いのか。もしかして脳に異常があるのではないか。見た目ではわからないが、彼自身にやる気がないのかも知れない。僕は悩んでいた。彼の家を訪ねるのが億劫になり、表情を作らない彼と対峙するのが怖かった。かつて穏やかだった彼の両親の表情が曇っていくのを見るのが辛かった。

ある時、僕が暗い顔で教科書を開くと、彼は左手を滑らかに動かして、すらすらと文字を打ち込んだ。ディスプレイに文字が流れていく。

「もううんざりだ。くだらない。馬鹿げてる。全部終わりでいい。全て終わりにしたい。ここには何にもなかった。死にたい。消してほしい。それこれと希望。ああなればいいという理想。それはどこにも行きつかなくて。やっぱり何にもなかった。現実だそれが。気持ち悪い。受け入れていい。映画とか漫画みたいに全てがうまくいくわけがなくて、要するに馬鹿だった！　いい話なんてものはない。どうせ死人の話だ。僕が馬鹿だから、無益な時間とお金を、たくさんの人に使わせた！　もうたくさんだ。十分だ。全て終わりでいいんだ。みんな楽になればいい。僕も楽になりたい！　しを！　くれ！」

僕は彼を宥めた。別な選択肢もあるはずだと説明した。例え数学ができなくても、例えば小説を書いてみるのはどうだろう。彼が背負っている境遇や感情は他の人にないものだ。だからきっと心に響くものができるのではないか。そんなことを話した。

彼は無表情のままに憤慨した。荒々しい言葉で僕をなじり、自分を徹底的に卑下した。見たことのない勢いで文字が流れていく。それは言葉を成していないほど興奮していた。どうにか事情を聞き取ると、僕が来るよりも前に多くの家庭教師が招かれ、様々な分野に挑戦させられてきたのだという。そしてその全てはうまくいかなかった。繰り返し挫折することに疲れ果ててしまったのだ。表情の読み取れない彼だからわからなかった。家族の体裁を守るため取り繕ってきたけれど、初めから深い疲弊と絶望の中にあったのだ。

今や理性の堤防は決壊した。どれだけ問答を繰り返しても、彼の意思は変わらなかった。けれど、僕は一つの光明を見た。彼に必要なのは数学ではなかったのだと悟った。ハンデを背負いながら、努力して才能を花ひらく、そんな絵に描いたような人間である必要は全くない。少しもない。誰かのために生きる必要はない。それを知ることがただ必要なのだと思った。ありのままで生きていても良いのだという赦し、それを自分に与えるべきなのだ。僕は熱を込めて説明した。

しかしけれど、その思いが届くことはなかった。彼は、光るもののない人生は虚無でしかなく、枯れた未来に絶望を抱きながら生きていくことはできないと断じた。一等激しい言葉を残して、彼は心を閉ざしてしまった。何を呼び掛けても、指先を動かすことをやめてしまった。医者も彼がどうなったのか判断できなかった。自らの意思で反応することをやめてしまったのか。正気を失ったのか。左手の筋肉さえも麻痺してしまったのか。

両親は狼狽し、それでも一縷の望みをかけて、点滴を打ち、生命維持を望んだ。しかし僕は、彼の残した記録の全てを打ち明けた。そして、全ての医療措置を絶つことこそが、彼の望みではないかと説明した。最も大切にしていたものが、最も大切にしていた行いが、それ自身を損なっていた可能性。彼の両親は、まともに受け入れられなかった。混乱し正気でいられなかった。全てが歪んでしまったようだった。居合わせた誰もが泣き叫んでいた。

最終的に僕は、見舞いと称して彼の点滴に食塩水を混ぜた。なるべく、速やかに死ねるように、濃度が高くなるようにしたつもりだが、それに意味があったかどうかはわからない。彼には苦痛の表情さえも現れないからだ。ただ、今際の際に、彼の左手がかすかに動いたのを見た気がする。ただ、ディスプレイに一つの言葉が残されていた。

「ゆめ」

肯定的にも否定的にも読むことができる。あるいはただの偶然かも知れない。それを知るすべは僕らにはない。こうして僕は人の命を奪った。事件は速やかに処理され、僕は逮捕された。裁判が行われ、執行猶予つきの懲役刑が与えられた。それとは別に、言い渡された慰謝料は一億と二千万。僕はそれを受け入れた。

* 2

カーテンの隙間からこぼれる光で目を覚ました。仕事が始まるまで、まだかなりの時間がある。ぼんやりした頭で、ゲームを起動する。これが、日課になっている。オートボタンを押して、勝手に動く画面からは、もう視線を切っていた。改めて考えてみると、とても馬鹿馬鹿しいことをしているなと思う。さっさと辞めてしまえば良いのに。それでも続けている理由は自分でもよくわからない。ただ流されていく木の葉のように、一番近い浅瀬に漂着する。それと似ている。意思はない。とても悲しい。内容を確認せずにOKボタンを押す。その繰り返し。僕がゲームを遊んでいるのではなくて、僕はゲームに遊ばれている？　いや、そんなことはない。ただ、やはり、とても悲しいと思った。

ふと、通知欄に一つのメッセージが光っているのに気づいた。「そろそろ、いいんじゃないの？」要件のはっきりしない一言に、覚えのないサイトのリンクが貼り付けられている。スパムメールだ。指先を弾いて、アーカイブに放り込む。と、操作し切った後に、考え直した。ちらりと見えた差出人のアイコンが、知っている人のそれだったような気がしたからだ。

アーカイブに入って、先頭のメールを確認すると、やはり見覚えのあるアイコンがそこにあった。眠そうな顔をしているうさぎ「バニ」だ。僕が高校生の頃に流行ったゲームのキャラクターだ。いくつかシリーズになっていたけれど、今では続編も出ていない。とても懐かしい気持ちになった。バニを自分の持ちキャラにしていたアルミは元気にしているだろうか。

アルミや仲間たちのことを思い出す。僕らはとても愚かで単純だったので、家に集まってゲームをすることに青春の大半を費やした。スーパーファミコンから始まって、プレイステーションを遊んで、ニンテンドー64も遊んで、それから何故かファミコンに戻った。パソコンを触れるようになってから個人制作のフリーゲームもレパートリーに加わった。

どうしようもなく楽しかった。少ないお小遣いでも、仲間を集めればいくらかのゲームを買い込むことはできる。だから僕らは、少ない予算を分かち合って、ゲームを買った。それは、枯れることのない井戸のように僕らを潤した。浴びるようにゲームをして、馬鹿みたいに遊んだ。誰かの両親に馬鹿だと罵られた。修学旅行にだってゲームを持ち込んで、旅館に隠れ、夢中で遊んだ。そうして帰りの新幹線に乗り遅れて、しこたま怒られた。すべて、目が滲むほど懐かしい。その世界で、特別ゲームセンスのあったアルミは、僕らのヒーローだった。彼女に何度も挑んで、ボロボロに負けた毎日があった。悔しげにうめく僕らを、彼女は満足そうに見下ろしていた。何をやらせても上手いのは、それだけ練習しているということの証でもあった。初めは下手だった彼女があっという間に腕を上げてくるのは、僕らより前のめりだったからだろう。

そんなアルミとの縁も、高校を卒業してから、ぱったりと途切れてしまった。僕たちはみな、成長するに従って、命を燃やすような生き方はできなくなった。だから、彼女のことも顧みることが出来なかった。それが今、一体どうしてこんな謎めいたメッセージを送りつけてきたのだろう。わからない。それを知るためにも、僕は添付されたリンクを開いた。ファイルダウンロードが始まる。3分とたたずダウンロードは完了した。ともかくタップして開いてみた。

> polarstar.vrpg に対応するアプリケーションが見つかりません

エラーが表示されてしまったが vrpg という四文字には見覚えがあった。これは、僕らがかつて遊んでいたフリーゲームでよくみられたフォーマットだ。RPGを個人制作できるソフトで作られたことを表している。僕もアルミも、拙いながら触ったことはあった。ランタイムをインストールした上で、パソコンを使えば何らかのゲームが起動するはずだ。

僕は、押し入れに放り込んでいた年代物のパソコンを引っ張り出して、電源スイッチを押した。低音を立てながらOSのロゴが現れる。どうやらまだ生きている。埃を被ったキーボードとマウスを広げた。携帯からファイルを転送し、パソコンでファイルを受け取る。ダブルクリックで起動できるだろうか。ブラックアウトした数秒後に、アプリケーションは起動した。古めかしい8ビット風のテーマ曲と共に「ポーラスター」のタイトル文字が現れる。きっとこれが、アルミの最新作なのだろう。

時計をちらりと見る。ここまでたどり着くのに、随分時間がかかっていた。もう、逆立ちしたって仕事には間に合わない。これからしようとしている不道徳を前に、借金のことが頭によぎった。だが、一日くらいなら。僕は目を瞑って、会社に欠勤の連絡を入れた。こんな風に、社会に逆らってゲームをするのは久しぶりかもしれない。自然と笑みがこぼれる。すっかり迷いは消えて、高校生に戻ったような気持ちでスタートボタンを押していた。

* 3

ポラリス。揺るぎない不動の座。はるか北の地で生まれた少年に、その名は与えられた。彼は、森の中に住み猟師を生業とする貧しい家に生まれた。遠い系譜を辿れば、彼の一族は権力者として国を支配したこともある。しかし、国を追われて何世代も経た今では、それも霞と消えてしまった。ポラリスの母は、産褥熱のために命を落とした。

ポラリスは父に習って、獣たちを撃つすべを学んだ。仕留めた獲物はナイフを使って皮を剥ぎ、骨を外し、肉を切り分ける。寡黙な父はいつも仕事にポラリスを連れていき、狩りの手法を教えた。獣たちの鳴き声や習性、足跡の追い方、縄張りやフンの見分け方、急所について。ポラリスの眼前で、獣たちの命が明滅していく。ついさっきまで、生き生きと躍動していた獣が、撃たれ、もがき、虚な目で死んでいく。それは彼にある種の諦観を植え付けた。人もまた獣であり、いつかそのような死を迎えるのだろう。彼は、漠然とそう考えていた。

時にはいくらかの人が訪れ、そして去っていく。行商人と、ありものを交換する。それは、あまりにささやかなものだ。鹿の毛皮や角を手放して、陶器のカップを手に入れたり、使えない猟犬をそばに置いたりするだけだ。作物の育たないこの地域では、総生産は非常に低い。まともな医療もない。だから、彼が大人になるだけの時間が流れても、ほとんど集落の人口は変わらなかった。

父は母の命日が近づくたびに、端材を使って鳥の置物を作った。手のひらに収まるほどの小ぶりのものだ。生前の母は、その鳥が好きだったのだという。年が過ぎるたび、窓際に並ぶ鳥たちが増えていくのだった。ポラリスもそれを真似て、毎年一つ、不恰好な鳥を作るようになっていた。

ポラリスが一人で狩りに出ることを認められた頃、凶暴な鬼が集団で村を襲っているという噂が流れ始めた。それは、人の形を成してはいるものの肌は青く、意思疎通は不可能であり、破壊のかぎりを尽くすのだという。すでに、魔物に滅ぼされた集落が無数にあるらしい。村の男たちは協力して集落の要塞化を試みることになった。

しかし悲劇は訪れた。ポラリスたちがどれだけ集落を堅固にしたところで、鬼たちはそれを意に介さなかった。彼らの武器は粗末な棍棒であったが、肥大した筋肉から振るわれるそれは、明らかに人類のいかなる武器よりも強力であった。どんな罠も、ものともせず根こそぎ破壊し、土塁を吹き飛ばした。抵抗したものは、次の瞬間に首のない死体となって転がっている。父は果敢に立ち向かい、銃を使って数匹の鬼を仕留めたが、それまでだった。怒りを買った父は骨も残らないほど粉砕されてしまった。残された血溜まりに、ポラリスは震え上がり、立ち上がることもできなくなった。

備えを突破された集落は、あまりにも脆かった。屍が山を成し、残されたものたちは捕らえられた。獣たちの命を容易く奪ってきた自分達が、鬼に蹂躙されるのは自然の摂理なのだろう。ポラリスは死を覚悟した。

しかし、ポラリスを待っていたのは死ではなく過酷な肉体労働だった。鬼たちは王によって統率されており、言語を持ち、文明を築いていた。王は自らの都を作るための労働力を求めていた。ポラリスは四六時中の間、土木作業を強制された。鬼たちの圧倒的暴力を目の当たりにして以来、彼は抵抗するのをやめていた。ただ従順に使い潰されていった。

やがて、母の命日が近づいてきた。彼は記憶の片隅から、鳥の置物のことを思い出した。ポラリスはわずかな休憩時間を縫って、寝る間を惜しんで工作に没頭した。やり場のない感情をぶつけていたのかもしれない。月が満ち、欠けて消え、また満ちる頃、ようやくそれは完成した。これまでに彼が作ったどの置物よりも研ぎ澄まされていた。石で削り、砂で磨いた面は滑らかで、触ると温かみが感じられるような気がした。彼は満足気に頷くと、ばたりと意識を失った。

鬼の子供たちが騒いでいる。倒れたポラリスを見物にやって来たのだ。度重なる重労働と睡眠不足、栄養不足によって、ポラリスは虫の息だった。大人の鬼がやってくる。彼はポラリスをつまみあげ、骨塚に捨て去った。しかし、すぐさま女の鬼が歩み寄ってきた。他の鬼と一線を画した金の刺繍から王族のそれとわかる。彼女はポラリスを軽々と持ち上げ、子供を抱くように、小脇に抱えて連れ去っていった。空いた方の手にはポラリスの鳥を優しく握っている。

* 4

# 時には、助けを求めるものがいる。そこで与えられる選択肢は、助けるか助けないかという単純な二択だ。僕はゲームをリセットしながら、二つの選択肢のどちらも試してみたが、どちらを選んだとしてもあまり意味はなかった。それは遭難者に見せかけた野盗であったり、集落を支配しようとする侵略者であったりした。気の狂った犯罪者もいた。ともかく、誰も彼も、ろくでもない訪問者ばかりだった。同じ集落の仲間でさえも、貧しさや嫉妬からポラリスに牙を剥いた。ポラリスの家は簡素なものだし、彼が襲われる言われはないのだが、それでも人々は、彼から奪い取ろうとするのだった。僕はポラリスを操作して、それらに対峙した。

# アルミが作っただけあって、適当に操作していたらあっという間にゲームオーバーになるような難易度に設定されている。でも、その手応えが心地良い。僕は腰を据えてこのゲームに取り組んでいたので、長く足止めを食らうことはなかった。

# ゲームの中で一年の月日が流れた。集落の男が大慌てでやってくる。勇者が魔王を討ったのだという。彼は大喜びしていたが、ポラリスは無感動なまま立ち尽くしていた。実際、彼の身の回りは全く変化がなかった。野盗は減らないし、魔物が迷い込んでくるのも変わらない。その暮らしの中に彼はあって、それ以外の出来事は遠い世界のままでしかなかった。魔王が消えた世界では、共通の敵を失った人間たちの戦争が始まった。奪い奪われる戦い。戦火は広がり、そしてそこから逃れようとする者たちが北へ北へとやってくる。

# ポラリスたちのいる集落にも、故郷を失った難民が訪れた。難民を追い払うか、迎え入れるかの選択肢が現れた。僕は素直に難民を受け入れることを選んだ。その結果、難民たちは食料を食い潰し、それに怒った友人を殺して、財産を奪い去っていった。代わり映えのしなかったマップが血で染まり、路傍には打ち捨てられた死体が転がっていた。唯一の家族、使えない猟犬も、蹴られて死んでいた。ポラリスは、一人取り残された。僕はひどく動揺してリセットした。

# 僕は集落が滅びるのを避けるために、難民たちを拒絶した。難民たちは怒り、特に荒くれ者たちは襲いかかってきた。彼らは決して強者ではなかった。遠く逃げ落ちる旅の中で体力を失っていたのだろう。あっけなく倒れた。戦えない老人や女子供は逃げ惑い、姿を消した。数日と経たないうちに、雪の中に埋もれた死体が大量に見つかった。僕は修羅だ非人間だと唾を吐きかけられ、石を投げられた。もはや村で生きていくことはできなかった。

# いずれも正解ではなかった。背後にいるアルミが、いかなる選択も、世界に影響を及ぼすことはできないのだと語っている気がした。

ポラリスは旅に出た。彼は、これまで遠くへ行った経験がなかったから、文字通り世間知らずだった。言葉も、文化も、ものの価値も知らない。馬鹿にされたり、騙されたりする。それでも、少しずつ変化していく。旅仲間に、猟犬を失ったことを話す。名前は何だったのかと問われる。名前はなかったと答える。墓を作ることもできないな、と静かに憐れみを受ける。それ以上、物語られることはない。善も悪も語らないその世界観が、僕には心地良く感じられた。

学んだり失ったりしながら、荷物も仲間も増えないまま、流れに流れて、聖地と呼ばれる土地にやってきた。それがいかなる理由でそう呼ばれているのかはわからない。そこに信仰はない。宗教的意義もない。豊かではなく、文化的ではなく、平和でもなかった。物々しく隔離区域と書かれた看板がある。ポラリスはその領域に足を踏み入れた。

朽ちた釣り堀がある。長い坂道の右手には痩せたぶどう畑がある。そのぶどう畑を二分するように大きな屋敷があり、向かいには石切場がある。街人は一人として見えない。丘の上には小さな家が寄り添うように集まっている。あちこちに、焦げたような痕跡がある。どの家も中身は空っぽだ。細かく調べていくと、子供が隠れているのを見つけた。彼は秘密基地を作っているのだと言った。汚れたマットに漫画雑誌が置かれている。彼はそれだけ言って逃げていった。

思わずため息が漏れた。このノスタルジックな演出が、僕の記憶を刺激した。僕はこれと似た秘密基地を作っていたことがある。丘の上の家に住んでいて、ぶどう畑でかくれんぼをしたことがある。そんな時代が確かにあった。当時のことを思い出すほど、隔離区域にある街並みが、僕の故郷に似ていることに気づいた。瓦礫だらけの小屋は、まさに僕の住んでいた家の間取りと一致する。

ただ、一体どうしてこれほど破壊されてしまったのだろうか。壁は吹き飛ばされて、炭のようになっている。家財道具も見る影もない。妙に胸がざわついた。僕は、ゲームの中でアルミの家を探した。丘を超えたトンネルの先にある、二階建てのこぎれいな家。ゲームにどっぷりはまる前には、広い庭でキャッチボールをしたり、木登りをしたこともある。そんな爽やかな記憶に満ちた場所。

しかしそこには、全てを削りとったような深い深い穴があるだけだった。何か許すべからざるものを剥ぎ取ったような、そんな風にも見えた。これは架空の物語の一風景に過ぎないと言うのに、僕は暗い気持ちになった。

ポラリスはその大穴に興味を持ち、情報収集を始めた。しかし、街の人々はその場所に触れることを嫌がった。渋々語ることも抽象的でよくわからなかった。彼らが言うには、そこは、爆心地なのだと言う。汚れと、苦しみと、怒りと、理不尽と、不幸の始まりの場所なのだと言った。隔離して保存して置かねばならないのだと言った。

しつこく聞き込みを続けていると、警ら隊に拘束されてしまった。鋼のように無機質で強靭な男たちになすすべもなく連れ去られる。そしてポラリスは大穴に突き飛ばされてしまった。果てしない闇の中に吸い込まれていく。何か選択肢を誤っただろうか。落ちて砕けて、そこで、ゲームはおしまいなのかも知れない。考えるだけの時間がある。どこまでも落ちていく。不思議の国のアリスみたいだなと思った。終わりはやってこない。落ちていくポラリスのそばに、誰かがやってくる。その誰かも、自由落下に身を任せている。一人二人と数が増え、いつしか画面を埋め尽くすほどになった。

死の記録が流れ込んでくる。奈落に落ちた人それぞれの記録がこびりついていて、圧縮されたその様を逆再生しているのだという。殺されて、奪われて、その繰り返しだ。ここにいるのは敗者ばかりだ。奪われた者たちの記録だ。胸が悪くなるような場面ばかりが再生された。言葉だけで描かれたものに過ぎず、リアリティは感じられなかったが、人が貶められ、辱められ、奪われていく様を反復されるのは良いものではなかった。

そして、最後に再生されたのは、アルミという少女の記録だった。この街に生まれて、ゲームの世界に没入した少女の記録だった。

彼女は進学しなかった。どこへも行かないことを選んだ。社会の人との繋がりを失った彼女は、より空想にふけるようになった。社会不適合だと自虐しながら、いつまでもゲームに入り浸っていた。両親は初め、彼女を受け入れ、どうにか社会復帰させようとしていた。

しかし、どれだけ心を尽くしても、どれだけ時間を尽くしても彼女は全く変化しない。あらゆる愛情が素通りしてしまう。その絶望に絶えられず、父は壊れてしまった。

初めは酒に逃げて、家に寄り付かないようになる。愚痴をこぼす。まともな友人は呆れて離れていく。助け合うべき妻の心も離れていく。人間関係を失い、不安定になる。暴力を振るうようになる。日に日に悪化していくアルミの父と、全く変化のないアルミ。アルミの母は壊れていく家庭に耐えられなくなり、家を去る。家は荒んでいき、ゴミだらけになる。

そしてある日、すべてが決定的に壊れた。アルミの父は、アルミに暴力を振るい、そして彼女を陵辱した。社会の役に立たないなら、せめてこれぐらいはしろ。そう言ってゲラゲラ笑いながら、彼女を犯した。アルミは抵抗したが、吐くほど殴られて気絶させられた。

翌日、復讐に燃えた彼女は、家に火を放った。しかし、その試みはうまく行かなかった。優秀な消防隊によって、すぐさま消し止められてしまった。騒ぎを知った父は激怒し、彼女はより苛烈な暴力を浴びることになった。

アルミは火よりも深い憎しみと、怒りと呪いとを胸に抱いた。持て余した行き場のない狂気が、これまで愛してきたゲームという世界を投げ捨てさせた。彼女は代わりにスコップを手にとった。穴を掘る。合理的ではない。穴を掘って何かを解決しようとしているのではない。彼女は気が触れていた。ただ奈落へ、深淵への道を希求しているのであった。彼女は汗まみれになり、息を切らして喘ぎながら穴を掘った。貧弱な少女の力では、せいぜい人の半分ほどの深さにしかならなかった。

何日かけても、彼女は正気に戻らなかった。そして、狂気が濃くなるほどに穴は深く、不可視の悍ましいものが蓄積されていった。

彼女が完全に壊れるころ、それは完成した。闇色をしたマグマが噴き出し、全てを一瞬で覆い尽くしてしまった。彼女を蹂躙した父も、見向きもしなかった社会も全てを飲み込み、破壊し尽くした。ここで唐突に物語は終わってしまう。

セーブデータを遡って、何度繰り返しても同じ結末だった。他のエンディングはない。ネットでポーラスターを検索しても、全く別のページがヒットするばかりだった。そもそも、僕がこのゲームをダウンロードしたページさえも一般公開されていないらしく、このゲームの情報は一切見つからなかった。

* 5

僕はひどく動揺していた。ポーラスターのアルミは、現実のアルミではない。けれど、消息の知れないアルミがもし、同じ目に遭っていたとしたら。全てを噴火させたということは、命を絶ったということの暗示ではないか。憶測にすぎないが、彼女ならやりかねないと思った。

僕は何年もログインしていないSNSサービスをいくつか使って、彼女の名前を探した。しかし、足取りは一切つかめなかった。目の疲れを感じて、パソコンから離れる。ソファに身を任せて、目を瞑った。

僕が考えることをやめて機械的に働いていた間に、彼女は自分の生き方を貫こうとしていたのだろう。負けず嫌いだった彼女のことを思い出す。あんなに輝いていたのに。あんなに特別だったのに。ほんの少しでも僕が動いて、関わりを持っていたら、未来は変わっていただろうか。希望を与えることができただろうか。不安と悲しみと後悔で胸がいっぱいになった。

# 家庭が壊れ、実父に襲われたとき、どれほどの絶望を抱えていただろう。そんな中で記録のためにポーラスターを作り上げた執念を想像する。あれだけのボリュームだ。一朝一夕に作れるとは思えない。少なくとも一ヶ月はかかったのではないだろうか。無我夢中で作っていただろう。それに彼女が満足したなら、作り上げてからどうなったのかは、どこにも描かれていない。
