* 1

僕は、心を無にして体を動かしていた。作業服を着て、なんだかよくわからない荷物を運ぶだけのアルバイトだ。つまらない仕事だけれど、脳を使わずにお金を稼ぐことができる。どれだけ体がきしんだところで、心は傷まないから、安らかなままでいられる。それくらいが身の丈にあっている。

大手通販サイトが管理するこの巨大倉庫の中では、自分がミニチュア模型みたいに、ちっぽけな存在だということがわかる。すれ違う男たちは、帽子をかぶって目を合わさないようにしている。餌を運ぶ蟻のような気もするし、酸素を運ぶヘモグロビンのような気もする。いずれにしても、巨大なシステムの一部なのは違いない。高度な機械化が進んだ今でも、人間が酷使されているのは、僕らがあまりにも安いからだろう。そして僕たちは、それを受け入れねばならないほど、明らかに貧しい。

生きていくための仕事が終わって、崩れ落ちるようにアパートの床に転がった。帰りがけに買ったランチパックをかじりながら、画面をタップするだけのゲームで時間を潰した。今日はもう休もう。明かりを消して、布団に体を横たえて、不思議だなと思った。生きていることの不思議。生きていけることの不思議。

* 2

カーテンの隙間からこぼれる光で目を覚ました。携帯を見やると、通知欄に一つのメッセージが光っているのに気づいた。「そろそろ、いいんじゃないの？」要件のはっきりしない一言に、覚えのないサイトのリンクが貼り付けられている。スパムメールだ。指先を弾いて、アーカイブに放り込む。…いや。差出人のアイコンに見覚えがあった。

アーカイブの先頭のメールを確認すると、確かに「バニ」のアイコンがあった。何年も前に流行ったゲームのキャラクターだ。眠そうな顔をしているこのうさぎは、とても扱いにくい、いわゆる色物キャラクターだった。当時の僕らの周りで、唯一バニを使っていた友人の名を思い出す。アルミ。彼女はそんなニックネームを使っていた。

アルミや仲間たちのことを思い出す。僕らはとても愚かで単純だったので、家に集まってゲームをすることに青春の大半を費やした。スーパーファミコンから始まって、プレイステーションを遊んで、ニンテンドー64も遊んで、それから何故かファミコンに戻った。パソコンを触れるようになってから個人制作のフリーゲームもレパートリーに加わった。

どうしようもなく楽しかった。少ないお小遣いでも、仲間を集めればいくらかのゲームを買い込むことはできる。だから僕らは、少ない予算を分かち合って、ゲームを買った。それは、枯れることのない井戸のように僕らを潤した。浴びるようにゲームをして、馬鹿みたいに遊んだ。誰かの両親に馬鹿だと罵られた。修学旅行にだってゲームを持ち込んで、旅館に隠れ、夢中で遊んだ。そうして帰りの新幹線に乗り遅れて、しこたま怒られた。すべて、目が滲むほど懐かしい。その世界で、特別ゲームセンスのあったアルミは、僕らのヒーローだった。彼女に何度も挑んで、ボロボロに負けた毎日があった。悔しげにうめく僕らを、彼女は満足そうに見下ろしていた。何をやらせても上手いのは、それだけ練習しているということの証でもあった。初めは下手だった彼女があっという間に腕を上げてくるのは、僕らより前のめりだったからだろう。

そんなアルミとの縁も、高校を卒業してから、ぱったりと途切れてしまった。僕たちはみな、成長するに従って、命を燃やすような生き方はできなくなった。だから、彼女のことも顧みることが出来なかった。それが今、一体どうしてこんな謎めいたメッセージを送りつけてきたのだろう。わからない。それを知るためにも、僕は添付されたリンクを開いた。ファイルダウンロードが始まる。3分とたたずダウンロードは完了した。ともかくタップして開いてみた。

> polerstar.vrpg に対応するアプリケーションが見つかりません

エラーが表示されてしまったが vrpg という四文字には見覚えがあった。これは、僕らがかつて遊んでいたフリーゲームでよくみられたフォーマットだ。RPGを個人制作できるソフトで作られたことを表している。僕もアルミも、拙いながら触ったことはあった。ランタイムをインストールした上で、パソコンを使えば何らかのゲームが起動するはずだ。

僕は、押し入れに放り込んでいた年代物のパソコンを引っ張り出して、電源スイッチを押した。低音を立てながらOSのロゴが現れる。どうやらまだ生きている。埃を被ったキーボードとマウスを広げた。携帯からファイルを転送し、パソコンでファイルを受け取る。ダブルクリックで起動できるだろうか。ブラックアウトした数秒後に、アプリケーションは起動した。古めかしい8ビット風のテーマ曲と共に「ポーラスター」のタイトル文字が現れる。きっとこれが、アルミの最新作なのだろう。

時計をちらりと見る。ここまで来るのに、随分時間がかかっていた。もう、逆立ちしたって仕事には間に合わない。こんな風に、社会に逆らってゲームをするのは久しぶりかもしれない。そう思うと、かえって楽しくなってきた。僕は、ただ一人、気持ちの悪い笑みを浮かべながら、スタートボタンを押した。

* 3

ポーラスターの物語は、孤独な主人公から始まる。彼は寒い地域の生まれで、一人で森へ入り、鹿や鳥を撃ちながら暮らしている。遠く離れた地では勇者が生まれ、魔王が生まれたのだという。そんなモノローグを挟みながらも、主人公はどこへも行かない。稀に迷い込んで来る魔物と戦いが起きる他は、静かな狩猟の日々を続けている。時にはいくらかの人が訪れ、そして去っていく。ありものを交換して、少しずつ変化する。それは、あまりにささやかなものだ。陶器のカップを手に入れたり、使えない猟犬をそばに置いたりするだけだ。発展と言えるほどのものはない。

時には、助けを求めるものがいる。そこで与えられる選択肢は、助けるか助けないかという単純な二択だ。僕はゲームをリセットしながら、二つの選択肢のどちらも試してみたが、どちらを選んだとしてもあまり意味はなかった。それは遭難者に見せかけた野盗であったり、集落を支配しようとする侵略者であったりした。気の狂った犯罪者もいた。ともかく、誰も彼も、ろくでもない訪問者ばかりだった。同じ集落の仲間でさえも、貧しさや嫉妬から主人公に牙を剥いた。主人公の家は簡素なものだし、彼が襲われる言われはないのだが、それでも人々は、彼から奪い取ろうとするのだった。僕は主人公を操作して、それらに対峙した。

アルミが作っただけあって、適当に操作していたらあっという間にゲームオーバーになるような難易度に設定されている。でも、その手応えが心地良い。僕は腰を据えてこのゲームに取り組んでいたので、
長く足止めを食らうことはなかった。

ゲームの中で一年の月日が流れた。集落の男が大慌てでやってくる。勇者が魔王を討ったのだという。彼は大喜びしていたが、主人公は無感動なまま立ち尽くしていた。実際、彼の身の回りは全く変化がなかった。野盗は減らないし、魔物が迷い込んでくるのも変わらない。その暮らしの中に彼はあって、それ以外の出来事は遠い世界のままでしかなかった。魔王が消えた世界では、共通の敵を失った人間たちの戦争が始まった。奪い奪われる戦い。戦火は広がり、そしてそこから逃れようとする者たちが北へ北へとやってくる。

主人公たちのいる集落にも、故郷を失った難民が訪れた。難民を追い払うか、迎え入れるかの選択肢が現れた。僕は素直に難民を受け入れることを選んだ。その結果、難民たちは食料を食い潰し、それに怒った友人を殺して、財産を奪い去っていった。代わり映えのしなかったマップが血で染まり、路傍には打ち捨てられた死体が転がっていた。唯一の家族、使えない猟犬も、蹴られて死んでいた。主人公は、一人取り残された。僕はひどく動揺してリセットした。

僕は集落が滅びるのを避けるために、難民たちを拒絶した。難民たちは怒り、特に荒くれ者たちは襲いかかってきた。彼らは決して強者ではなかった。遠く逃げ落ちる旅の中で体力を失っていたのだろう。あっけなく倒れた。戦えない老人や女子供は逃げ惑い、姿を消した。数日と経たないうちに、雪の中に埋もれた死体が大量に見つかった。僕は修羅だ非人間だと唾を吐きかけられ、石を投げられた。もはや村で生きていくことはできなかった。

いずれも正解ではなかった。背後にいるアルミが、いかなる選択も、世界に影響を及ぼすことはできないのだと語っている気がした。

主人公は旅に出た。彼は、これまで遠くへ行った経験がなかったから、文字通り世間知らずだった。言葉も、文化も、ものの価値も知らない。馬鹿にされたり、騙されたりする。それでも、少しずつ変化していく。旅仲間に、猟犬を失ったことを話す。名前は何だったのかと問われる。名前はなかったと答える。墓を作ることもできないな、と静かに憐れみを受ける。それ以上、物語られることはない。善も悪も語らないその世界観が、僕には心地良く感じられた。

学んだり失ったりしながら、荷物も仲間も増えないまま、流れに流れて、聖地と呼ばれる土地にやってきた。それがいかなる理由でそう呼ばれているのかはわからない。そこに信仰はない。宗教的意義もない。豊かではなく、文化的ではなく、平和でもなかった。物々しく隔離区域と書かれた看板がある。主人公はその領域に足を踏み入れた。

朽ちた釣り堀がある。長い坂道の右手には痩せたぶどう畑がある。そのぶどう畑を二分するように大きな屋敷があり、向かいには石切場がある。街人は一人として見えない。丘の上には小さな家が寄り添うように集まっている。あちこちに、焦げたような痕跡がある。どの家も中身は空っぽだ。細かく調べていくと、子供が隠れているのを見つけた。彼は秘密基地を作っているのだと言った。汚れたマットに漫画雑誌が置かれている。彼はそれだけ言って逃げていった。

思わずため息が漏れた。このノスタルジックな演出が、僕の記憶を刺激した。僕はこれと似た秘密基地を作っていたことがある。丘の上の家に住んでいて、ぶどう畑でかくれんぼをしたことがある。そんな時代が確かにあった。当時のことを思い出すほど、隔離区域にある街並みが、僕の故郷に似ていることに気づいた。瓦礫だらけの小屋は、まさに僕の住んでいた家の間取りと一致する。

ただ、一体どうしてこれほど破壊されてしまったのだろうか。壁は吹き飛ばされて、炭のようになっている。家財道具も見る影もない。妙に胸がざわついた。僕は、ゲームの中でアルミの家を探した。丘を超えたトンネルの先にある、二階建てのこぎれいな家。ゲームにどっぷりはまる前には、広い庭でキャッチボールをしたり、木登りをしたこともある。そんな爽やかな記憶に満ちた場所。

しかしそこには、全てを削りとったような深い深い穴があるだけだった。何か許すべからざるものを剥ぎ取ったような、そんな風にも見えた。これは架空の物語の一風景に過ぎないと言うのに、僕は暗い気持ちになった。

主人公はその大穴に興味を持ち、情報収集を始めた。しかし、街の人々はその場所に触れることを嫌がった。渋々語ることも抽象的でよくわからなかった。彼らが言うには、そこは、爆心地なのだと言う。汚れと、苦しみと、怒りと、理不尽と、不幸の始まりの場所なのだと言った。隔離して保存して置かねばならないのだと言った。

しつこく聞き込みを続けていると、警ら隊に拘束されてしまった。鋼のように無機質で強靭な男たちになすすべもなく連れ去られる。そして主人公は大穴に突き飛ばされてしまった。果てしない闇の中に吸い込まれていく。何か選択肢を誤っただろうか。落ちて砕けて、そこで、ゲームはおしまいなのかも知れない。考えるだけの時間がある。どこまでも落ちていく。不思議の国のアリスみたいだなと思った。終わりはやってこない。落ちていく主人公のそばに、誰かがやってくる。その誰かも、自由落下に身を任せている。一人二人と数が増え、いつしか画面を埋め尽くすほどになった。

死の記録が流れ込んでくる。奈落に落ちた人それぞれの記録がこびりついていて、圧縮されたその様を逆再生しているのだという。殺されて、奪われて、その繰り返しだ。ここにいるのは敗者ばかりだ。奪われた者たちの記録だ。胸が悪くなるような場面ばかりが再生された。言葉だけで描かれたものに過ぎず、リアリティは感じられなかったが、人が貶められ、辱められ、奪われていく様を反復されるのは良いものではなかった。

そして、最後に再生されたのは、アルミという少女の記録だった。この街に生まれて、ゲームの世界に没入した少女の記録だった。

彼女は進学しなかった。どこへも行かないことを選んだ。社会の人との繋がりを失った彼女は、より空想にふけるようになった。社会不適合だと自虐しながら、いつまでもゲームに入り浸っていた。両親は初め、彼女を受け入れ、どうにか社会復帰させようとしていた。

しかし、どれだけ心を尽くしても、どれだけ時間を尽くしても彼女は全く変化しない。あらゆる愛情が素通りしてしまう。その絶望に絶えられず、父は壊れてしまった。

初めは酒に逃げて、家に寄り付かないようになる。愚痴をこぼす。まともな友人は呆れて離れていく。助け合うべき妻の心も離れていく。人間関係を失い、不安定になる。暴力を振るうようになる。日に日に悪化していくアルミの父と、全く変化のないアルミ。アルミの母は壊れていく家庭に耐えられなくなり、家を去る。家は荒んでいき、ゴミだらけになる。

そしてある日、すべてが決定的に壊れた。アルミの父は、アルミに暴力を振るい、そして彼女を陵辱した。社会の役に立たないなら、せめてこれぐらいはしろ。そう言ってゲラゲラ笑いながら、彼女を犯した。アルミは抵抗したが、吐くほど殴られて気絶させられた。

翌日、復讐に燃えた彼女は、家に火を放った。しかし、その試みはうまく行かなかった。優秀な消防隊によって、すぐさま消し止められてしまった。騒ぎを知った父は激怒し、彼女はより苛烈な暴力を浴びることになった。

アルミは火よりも深い憎しみと、怒りと呪いとを胸に抱いた。持て余した行き場のない狂気が、これまで愛してきたゲームという世界を投げ捨てさせた。彼女は代わりにスコップを手にとった。穴を掘る。
合理的ではない。穴を掘って何かを解決しようとしているのではない。彼女は気が触れていた。ただ奈落へ、深淵への道を希求しているのであった。彼女は汗まみれになり、息を切らして喘ぎながら穴を掘った。貧弱な少女の力では、せいぜい人の半分ほどの深さにしかならなかった。

何日かけても、彼女は正気に戻らなかった。そして、狂気が濃くなるほどに穴は深く、不可視の悍ましいものが蓄積されていった。

彼女が完全に壊れるころ、それは完成した。闇色をしたマグマが噴き出し、全てを一瞬で覆い尽くしてしまった。彼女を蹂躙した父も、見向きもしなかった社会も全てを飲み込み、破壊し尽くした。

* 4

僕はひどく動揺していた。ポーラスターの物語は現実ではない。しかし、現実ではないにせよ、その一端は繋がっているはずだ。この物語を生み出した彼女の身に起きたことと、この世界の出来事が全く無縁であるとは思えなかった。
