* 1

僕は、心を無にして体を動かしていた。作業服を着て、なんだかよくわからない荷物を運ぶだけのアルバイトだ。つまらない仕事だけれど、脳を使わずにお金を稼ぐことができる。どれだけ体がきしんだところで、心は傷まないから、安らかなままでいられる。それくらいが身の丈にあっている。

大手通販サイトが管理するこの巨大倉庫の中では、自分がミニチュア模型みたいに、ちっぽけな存在だということがわかる。すれ違う男たちは、帽子をかぶって目を合わさないようにしている。餌を運ぶ蟻のような気もするし、酸素を運ぶヘモグロビンのような気もする。いずれにしても、巨大なシステムの一部なのは違いない。高度な機械化が進んだ今でも、人間が酷使されているのは、僕らがあまりにも安いからだろう。そして僕たちは、それを受け入れねばならないほど、明らかに貧しい。

生きていくための仕事が終わって、崩れ落ちるようにアパートの床に転がった。帰りがけに買ったランチパックをかじりながら、画面をタップするだけのゲームで時間を潰した。今日はもう休もう。明かりを消して、布団に体を横たえて、不思議だなと思った。生きていることの不思議。生きていけることの不思議。

* 2

カーテンの隙間からこぼれる光で目を覚ました。携帯を見やると、通知欄に一つのメッセージが光っているのに気づいた。「そろそろ、いいんじゃないの？」要件のはっきりしない一言に、覚えのないサイトのリンクが貼り付けられている。スパムメールだ。指先を弾いて、アーカイブに放り込む。…いや。差出人のアイコンに見覚えがあった。

アーカイブの先頭のメールを確認すると、確かに「バニ」のアイコンがあった。何年も前に流行ったゲームのキャラクターだ。眠そうな顔をしているこのうさぎは、とても扱いにくい、いわゆる色物キャラクターだった。当時の僕らの周りで、唯一バニを使っていた友人の名を思い出す。アルミ。彼女はそんなニックネームを使っていた。

アルミや仲間たちのことを思い出す。僕らはとても愚かで単純だったので、家に集まってゲームをすることに青春の大半を費やした。スーパーファミコンから始まって、プレイステーションを遊んで、ニンテンドー64も遊んで、それから何故かファミコンに戻った。パソコンを触れるようになってから個人制作のフリーゲームもレパートリーに加わった。

どうしようもなく楽しかった。少ないお小遣いでも、仲間を集めればいくらかのゲームを買い込むことはできる。だから僕らは、少ない予算を分かち合って、ゲームを買った。それは、枯れることのない井戸のように僕らを潤した。浴びるようにゲームをして、馬鹿みたいに遊んだ。誰かの両親に馬鹿だと罵られた。修学旅行にだってゲームを持ち込んで、旅館に隠れ、夢中で遊んだ。そうして帰りの新幹線に乗り遅れて、しこたま怒られた。すべて、目が滲むほど懐かしい。その世界で、特別ゲームセンスのあったアルミは、僕らのヒーローだった。彼女に何度も挑んで、ボロボロに負けた毎日があった。悔しげにうめく僕らを、彼女は満足そうに見下ろしていた。何をやらせても上手いのは、それだけ練習しているということの証でもあった。初めは下手だった彼女があっという間に腕を上げてくるのは、僕らより前のめりだったからだろう。

そんなアルミとの縁も、高校を卒業してから、ぱったりと途切れてしまった。僕たちはみな、成長するに従って、命を燃やすような生き方はできなくなった。だから、彼女のことも顧みることが出来なかった。それが今、一体どうしてこんな謎めいたメッセージを送りつけてきたのだろう。わからない。それを知るためにも、僕は添付されたリンクを開いた。ファイルダウンロードが始まる。3分とたたずダウンロードは完了した。ともかくタップして開いてみた。

> polerstar.vrpg に対応するアプリケーションが見つかりません

エラーが表示されてしまったが vrpg という四文字には見覚えがあった。これは、僕らがかつて遊んでいたフリーゲームでよくみられたフォーマットだ。RPGを個人制作できるソフトで作られたことを表している。僕もアルミも、拙いながら触ったことはあった。ランタイムをインストールした上で、パソコンを使えば何らかのゲームが起動するはずだ。

僕は、押し入れに放り込んでいた年代物のパソコンを引っ張り出して、電源スイッチを押した。低音を立てながらOSのロゴが現れる。どうやらまだ生きている。埃を被ったキーボードとマウスを広げた。携帯からファイルを転送し、パソコンでファイルを受け取る。ダブルクリックで起動できるだろうか。ブラックアウトした数秒後に、アプリケーションは起動した。古めかしい8ビット風のテーマ曲と共に「ポーラスター」のタイトル文字が現れる。きっとこれが、アルミの最新作なのだろう。

時計をちらりと見る。ここまで来るのに、随分時間がかかっていた。もう、逆立ちしたって仕事には間に合わない。こんな風に、社会に逆らってゲームをするのは久しぶりかもしれない。そう思うと、かえって楽しくなってきた。僕は、ただ一人、気持ちの悪い笑みを浮かべながら、スタートボタンを押した。

* 3

ポーラスターの物語は、孤独な主人公から始まる。彼は寒い地域の生まれで、一人で森へ入り、鹿や鳥を撃ちながら暮らしている。遠く離れた地では勇者が生まれ、魔王が生まれたのだという。そんなモノローグを挟みながらも、主人公はどこへも行かない。稀に迷い込んで来る魔物と戦いが起きる他は、静かな狩猟の日々を続けている。時にはいくらかの人が訪れ、そして去っていく。ありものを交換して、少しずつ変化する。それは、あまりにささやかなものだ。陶器のカップを手に入れたり、使えない猟犬をそばに置いたりするだけだ。発展と言えるほどのものはない。

時には、助けを求めるものがいる。そこで与えられる選択肢は、助けるか助けないかという単純な二択だ。僕はゲームをリセットしながら、二つの選択肢のどちらも試してみたが、どちらを選んだとしてもあまり意味はなかった。それは遭難者に見せかけた野盗であったり、集落を支配しようとする侵略者であったりした。気の狂った犯罪者もいた。ともかく、誰も彼も、ろくでもない訪問者ばかりだった。同じ集落の仲間でさえも、貧しさや嫉妬から主人公に牙を剥いた。主人公の家は簡素なものだし、彼が襲われる言われはないのだが、それでも人々は、彼から奪い取ろうとするのだった。僕は主人公を操作して、それらに対峙した。

アルミが作っただけあって、適当に操作していたらあっという間にゲームオーバーになるような難易度に設定されている。でも、その手応えが心地良い。僕は腰を据えてこのゲームに取り組んでいたので、
長く足止めを食らうことはなかった。

ゲームの中で一年の月日が流れた。集落の男が大慌てでやってくる。勇者が魔王を討ったのだという。彼は大喜びしていたが、主人公は無感動なまま立ち尽くしていた。実際、彼の身の回りは全く変化がなかった。野盗は減らないし、魔物が迷い込んでくるのも変わらない。その暮らしの中に彼はあって、それ以外の出来事は遠い世界のままでしかなかった。魔王が消えた世界では、共通の敵を失った人間たちの戦争が始まった。奪い奪われる戦い。戦火は広がり、そしてそこから逃れようとする者たちが北へ北へとやってくる。主人公たちのいる集落にも、故郷を失った難民が訪れる。難民を追い払うか、迎え入れるかの選択肢が現れた。僕は素直に難民を受け入れることを選んだ。その結果、難民たちは食料を食い潰し、それに怒った友人を殺して、財産を奪い去っていった。代わり映えのしなかったマップが血で染まり、路傍には打ち捨てられた死体が転がっていた。唯一の家族、使えない猟犬も、蹴られて死んでいた。主人公は、一人取り残された。僕はひどく動揺してリセットした。

僕は集落が滅びるのを避けるために、難民たちを拒絶した。難民たちは居場所を失い、雪の中に埋もれて何百人も命を落とした。その選択をした僕は非人間だとなじられ、村を追い出された。なんという理不尽だろう。けれど、それもアルミらしいのかもしれない。正解はない。良心もない。主人公は旅に出た。これまでどこへも行かなかったから、文字通り世間知らずだった。言葉も、文化も、ものの価値も知らない。馬鹿にされたり、騙されたりする。それでも、少しずつ変化していく。旅仲間に、猟犬を失ったことを話す。名前は何だったのかと問われる。名前はなかったと答える。墓を作ることもできないな、と静かに憐れみを受ける。それ以上、物語られることはない。それでも変化を感じるのだった。

学んだり失ったりしながら、荷物も仲間も増えないまま、流れに流れて、聖地と呼ばれる土地にやってきた。それがいかなる理由でそう呼ばれているのかはわからない。豊かではなく、文化的ではなく、平和でもなかった。街には丘があり、葡萄畑があった。滅多に発言しない主人公が突然に呟いた。「そうか、ここにあったのか」その言葉に何の説明もない。マップを探索してみる。葡萄畑の中央には大きな屋敷があり、向かいには石切場がある。そして、麓には釣り堀がある。世界観から少し外れた一連の建物を見て、僕は幼少の記憶を刺激された。葡萄畑にこっそり入って隠れんぼをした記憶がある。長い坂を自転車で超えられるか何度も試した記憶がある。この丘の半ばにあるボロボロの家で、何年も過ごした記憶が確かにある。そうだ、これはかつて、僕やアルミが住んでいた街の模倣なのかもしれない。
