* 1

僕は、心を無にして体を動かしていた。作業服を着て、なんだかよくわからない荷物を運ぶだけのアルバイトだ。つまらない仕事だけれど、脳を使わずにお金を稼ぐことができる。どれだけ体がきしんだところで、心は傷まないから、安らかなままでいられる。それくらいが身の丈にあっている。

大手通販サイトが管理するこの巨大倉庫の中では、自分がミニチュア模型みたいに、ちっぽけな存在だということがわかる。すれ違う男たちは、帽子をかぶって目を合わさないようにしている。餌を運ぶ蟻のような気もするし、酸素を運ぶヘモグロビンのような気もする。いずれにしても、巨大なシステムの一部なのは違いない。高度な機械化が進んだ今でも、人間が酷使されているのは、僕らがあまりにも安いからだろう。そして僕たちは、それを受け入れねばならないほど、明らかに貧しい。

生きていくための仕事が終わって、崩れ落ちるようにアパートの床に転がった。帰りがけに買ったランチパックをかじりながら、画面をタップするだけのゲームで時間を潰した。今日はもう休もう。明かりを消して、布団に体を横たえて、不思議だなと思った。生きていることの不思議。生きていけることの不思議。

* 2

カーテンの隙間からこぼれる光で目を覚ました。携帯を見やると、通知欄に一つのメッセージが光っているのに気づいた。「そろそろ、いいんじゃないの？」要件のはっきりしない一言に、覚えのないサイトのリンクが貼り付けられている。スパムメールだ。指先を弾いて、アーカイブに放り込む。…いや。差出人のアイコンに見覚えがあった。

アーカイブの先頭のメールを確認すると、確かに「バニ」のアイコンがあった。何年も前に流行ったゲームのキャラクターだ。眠そうな顔をしているこのうさぎは、とても扱いにくい、いわゆる色物キャラクターだった。当時の僕らの周りで、唯一バニを使っていた友人の名を思い出す。アルミ。彼女はそんなニックネームを使っていた。

アルミや仲間たちのことを思い出す。僕らはとても愚かで単純だったので、家に集まってゲームをすることに青春の大半を費やした。スーパーファミコンから始まって、プレイステーションを遊んで、ニンテンドー64も遊んで、それから何故かファミコンに戻った。パソコンを触れるようになってから個人制作のフリーゲームもレパートリーに加わった。

どうしようもなく楽しかった。少ないお小遣いでも、仲間を集めればいくらかのゲームを買い込むことはできる。だから僕らは、少ない予算を分かち合って、ゲームを買った。それは、枯れることのない井戸のように僕らを潤した。浴びるようにゲームをして、馬鹿みたいに遊んだ。誰かの両親に馬鹿だと罵られた。修学旅行にだってゲームを持ち込んで、旅館に隠れ、夢中で遊んだ。そうして帰りの新幹線に乗り遅れて、しこたま怒られた。すべて、目が滲むほど懐かしい。その世界で、特別ゲームセンスのあったアルミは、僕らのヒーローだった。彼女に何度も挑んで、ボロボロに負けた毎日があった。悔しげにうめく僕らを、彼女は満足そうに見下ろしていた。何をやらせても上手いのは、それだけ練習しているということの証でもあった。初めは下手だった彼女があっという間に腕を上げてくるのは、僕らより前のめりだったからだろう。

そんなアルミとの縁も、高校を卒業してから、ぱったりと途切れてしまった。僕たちはみな、成長するに従って、命を燃やすような生き方はできなくなった。だから、彼女のことも顧みることが出来なかった。それが今、一体どうしてこんな謎めいたメッセージを送りつけてきたのだろう。
