* 1

僕は、心を無にして体を動かしていた。作業服を着て、なんだかよくわからない荷物を運ぶだけの仕事だ。つまらない仕事だけれど、実入りは悪くない。何より、脳を使わずにお金を稼ぐことができる。どれだけ体がきしんだところで、心は傷まないから、安らかなままでいられる。それくらいが身の丈にあっている。

大手通販サイトが管理するこの巨大倉庫の中では、自分がミニチュア模型みたいに、ちっぽけな存在だということがわかる。すれ違う男たちは、帽子をかぶって目を合わさないようにしている。酸素を運ぶヘモグロビンのように、休むことなく働き続けている。僕らは、巨大なシステムに組み込まれたささやかな部品にすぎないのだ。高度な機械化が進んだ今でも、人間が酷使されているのは、僕らがあまりにも安いからだろう。そして僕たちは、それを受け入れねばならないほど、明らかに貧しい。

生きていくための仕事が終わって、崩れ落ちるようにアパートの床に転がった。帰りがけに買ったランチパックをかじりながら、家計簿アプリを見る。残る借金が一億七百二十八万と少し。絶望的に遠い金額だ。それでも、少しずつ少しずつ右肩下がりに減っている。生涯をかけて、返済することになるのだろうか。

三年前の事件を思い出す。あの頃の僕はもっとやる気がなくて、けれど悩みはなく、もっと生きている顔をしていたと思う。大学のつてで、家庭教師のアルバイトをしていた。人と関わりを持つことに関しては嫌いではなかったし、それなりに教えるのは得意だった。実際それまでに教えてきた生徒たちは、満足のいく成果を出していた。

その実績を認められて、とある家庭に招かれた。そうして出会った少年は、これまでにない事情を抱えていた。数年前から、重い病気を患い、半身が麻痺しているのだという。言葉を話すことができず、表情を作ることができなかった。ただ、左手の人差し指だけは負担なく動かすことができたので、わずかなフリック動作で文字を入力する専用の機械を作って、どうにかコミュニケーションを取っているらしい。

初めて対面した時、彼は唐突な依頼を持ちかけてきた。彼の腕に繋がっている点滴の輸液に十グラムの食塩を混ぜてほしい、と。明らかな自殺行為だった。彼の境遇を思うと、やむを得ないことなのかもしれない。自暴自棄にならないでほしい。僕はそう断った。彼は社会的弱者として、さんざん憐れみを受けて生きてきたのだろうと想像した。だから、僕は逆に、対等な人間として扱うべきだと考えた。

教えた科目は数学だった。数式を見せて、その意味を説明することはできたが、彼はなかなか問題を解くことができなかった。彼のために作られた機械は数式入力に対応していなかったせいだろう。そう考えて、彼の両親に依頼して、微分積分やら、漸化式や行列といった数式を書き出せるようにアップグレードをしてもらった。決して安い金額ではなかったようだが、彼の両親は惜しみなく資財を投じた。

家庭のサポートと彼自身の努力にもかかわらず、成果は芳しくなかった。僕は報酬のない残業をして彼の成績を伸ばそうとしたが、うまくいかなかった。原因がなんなのか、わからなかった。教え方が悪いのか。もしかして脳に異常があるのではないか。見た目ではわからないが、彼自身にやる気がないのかも知れない。僕は悩んでいた。彼の家を訪ねるのが億劫になり、表情を作らない彼と対峙するのが怖かった。かつて穏やかだった彼の両親の表情が曇っていくのを見るのが辛かった。

ある時、僕が暗い顔で教科書を開くと、彼は左手を滑らかに動かして、すらすらと文字を打ち込んだ。ディスプレイに文字が流れていく。

「もううんざりだ。くだらない。馬鹿げてる。全部終わりでいい。全て終わりにしたい。ここには何にもなかった。死にたい。消してほしい。それこれと希望。ああなればいいという理想。それはどこにも行きつかなくて。やっぱり何にもなかった。現実だそれが。気持ち悪い。受け入れていい。映画とか漫画みたいに全てがうまくいくわけがなくて、要するに馬鹿だった！　いい話なんてものはない。どうせ死人の話だ。僕が馬鹿だから、無益な時間とお金を、たくさんの人に使わせた！　もうたくさんだ。十分だ。全て終わりでいいんだ。みんな楽になればいい。僕も楽になりたい！　しを！　くれ！」

僕は彼を宥めた。別な選択肢もあるはずだと説明した。例え数学ができなくても、例えば小説を書いてみるのはどうだろう。彼が背負っている境遇や感情は他の人にないものだ。だからきっと心に響くものができるのではないか。そんなことを話した。

彼は無表情のままに憤慨した。荒々しい言葉で僕をなじり、自分を徹底的に卑下した。見たことのない勢いで文字が流れていく。それは言葉を成していないほど興奮していた。どうにか事情を聞き取ると、僕が来るよりも前に多くの家庭教師が招かれ、様々な分野に挑戦させられてきたのだという。そしてその全てはうまくいかなかった。繰り返し挫折することに疲れ果ててしまったのだ。表情の読み取れない彼だからわからなかった。家族の体裁を守るため取り繕ってきたけれど、初めから深い疲弊と絶望の中にあったのだ。

今や理性の堤防は決壊した。どれだけ問答を繰り返しても、彼の意思は変わらなかった。けれど、僕は一つの光明を見た。彼に必要なのは数学ではなかったのだと悟った。ハンデを背負いながら、努力して才能を花ひらく、そんな絵に描いたような人間である必要は全くない。少しもない。誰かのために生きる必要はない。それを知ることがただ必要なのだと思った。ありのままで生きていても良いのだという赦し、それを自分に与えるべきなのだ。僕は熱を込めて説明した。

しかしけれど、その思いが届くことはなかった。彼は、光るもののない人生は虚無でしかなく、枯れた未来に絶望を抱きながら生きていくことはできないと断じた。一等激しい言葉を残して、彼は心を閉ざしてしまった。何を呼び掛けても、指先を動かすことをやめてしまった。医者も彼がどうなったのか判断できなかった。自らの意思で反応することをやめてしまったのか。正気を失ったのか。左手の筋肉さえも麻痺してしまったのか。

両親は狼狽し、それでも一縷の望みをかけて、点滴を打ち、生命維持を望んだ。しかし僕は、彼の残した記録の全てを打ち明けた。そして、全ての医療措置を絶つことこそが、彼の望みではないかと説明した。最も大切にしていたものが、最も大切にしていた行いが、それ自身を損なっていた可能性。彼の両親は、まともに受け入れられなかった。混乱し正気でいられなかった。全てが歪んでしまったようだった。居合わせた誰もが泣き叫んでいた。

最終的に僕は、見舞いと称して彼の点滴に食塩水を混ぜた。なるべく、速やかに死ねるように、濃度が高くなるようにしたつもりだが、それに意味があったかどうかはわからない。彼には苦痛の表情さえも現れないからだ。ただ、今際の際に、彼の左手がかすかに動いたのを見た気がする。ただ、ディスプレイに一つの言葉が残されていた。

「ゆめ」

肯定的にも否定的にも読むことができる。あるいはただの偶然かも知れない。それを知るすべは僕らにはない。こうして僕は人の命を奪った。事件は速やかに処理され、僕は逮捕された。裁判が行われ、執行猶予つきの懲役刑が与えられた。それとは別に、言い渡された慰謝料は一億と二千万。少年の未来の値段。僕はそれを受け入れた。

* 2

カーテンの隙間からこぼれる光で目を覚ました。仕事が始まるまで、まだかなりの時間がある。ぼんやりした頭で、ゲームを起動する。これが、日課になっている。オートボタンを押して、勝手に動く画面からは、もう視線を切っていた。改めて考えてみると、とても馬鹿馬鹿しいことをしているなと思う。さっさと辞めてしまえば良いのに。それでも続けている理由は自分でもよくわからない。ただ流されていく木の葉のように、一番近い浅瀬に漂着する。それと似ている。意思はない。とても悲しい。内容を確認せずにOKボタンを押す。その繰り返し。僕がゲームを遊んでいるのではなくて、僕はゲームに遊ばれている？　いや、そんなことはない。ただ、やはり、とても悲しいと思った。

ふと、通知欄に一つのメッセージが光っているのに気づいた。「そろそろ、いいんじゃないの？」要件のはっきりしない一言に、覚えのないサイトのリンクが貼り付けられている。スパムメールだ。指先を弾いて、アーカイブに放り込む。と、操作し切った後に、考え直した。ちらりと見えた差出人のアイコンが、知っている人のそれだったような気がしたからだ。

アーカイブに入って、先頭のメールを確認すると、やはり見覚えのあるアイコンがそこにあった。眠そうな顔をしているうさぎ「バニ」だ。僕が高校生の頃に流行ったゲームのキャラクターだ。いくつかシリーズになっていたけれど、今では続編も出ていない。とても懐かしい気持ちになった。バニを自分の持ちキャラにしていたアルミは元気にしているだろうか。

アルミや仲間たちのことを思い出す。僕らはとても愚かで単純だったので、家に集まってゲームをすることに青春の大半を費やした。スーパーファミコンから始まって、プレイステーションを遊んで、ニンテンドー64も遊んで、それから何故かファミコンに戻った。パソコンを触れるようになってから個人制作のフリーゲームもレパートリーに加わった。

そんなアルミとの縁も、高校を卒業してから、ぱったりと途切れてしまった。僕たちはみな、成長するに従って、命を燃やすような生き方はできなくなった。だから、彼女のことも顧みることが出来なかった。それが今、一体どうしてこんな謎めいたメッセージを送りつけてきたのだろう。わからない。それを知るためにも、僕は添付されたリンクを開いた。ファイルダウンロードが始まる。3分とたたずダウンロードは完了した。ともかくタップして開いてみた。

> polarstar.vrpg に対応するアプリケーションが見つかりません

エラーが表示されてしまったが vrpg という四文字には見覚えがあった。これは、僕らがかつて遊んでいたフリーゲームでよくみられたフォーマットだ。RPGを個人制作できるソフトで作られたことを表している。僕もアルミも、拙いながら触ったことはあった。ランタイムをインストールした上で、パソコンを使えば何らかのゲームが起動するはずだ。

僕は、押し入れに放り込んでいた年代物のパソコンを引っ張り出して、電源スイッチを押した。低音を立てながらOSのロゴが現れる。どうやらまだ生きている。埃を被ったキーボードとマウスを広げた。携帯からファイルを転送し、パソコンでファイルを受け取る。ダブルクリックで起動できるだろうか。ブラックアウトした数秒後に、アプリケーションは起動した。古めかしい8ビット風のテーマ曲と共に「ポーラスター」のタイトル文字が現れる。きっとこれが、アルミの最新作なのだろう。

時計をちらりと見る。ここまでたどり着くのに、随分時間がかかっていた。もう、逆立ちしたって仕事には間に合わない。これからしようとしている不道徳を前に、借金のことが頭によぎった。だが、一日くらいなら。僕は目を瞑って、会社に欠勤の連絡を入れた。こんな風に、社会に逆らってゲームをするのは久しぶりかもしれない。自然と笑みがこぼれる。すっかり迷いは消えて、高校生に戻ったような気持ちでスタートボタンを押していた。

* 3

何のストーリーも示されないまま、主人公はどこかの街に降り立った。粗末なモデリングの道路を道なりに歩いてみる。フェンスで囲われた建物がある。手書き風の看板をみると、釣り堀のようだ。かすかに水音が聴こえるほかは、静まり返っている。駐車場はがら空きで、やはり人影は見当たらなかった。そのまま、奥の坂道を進んでみる。右手にはまだ青いぶどう畑が見えた。そういえば、小さな頃はぶどう畑の近くに住んでいたっけ。こんな坂道を通って、学校に歩いていた。懐かしく思いながら歩けば歩くほど、周囲の風景が、自分の記憶と似通っていることに気がついた。もしかして、この場所は…。

振り返ると、取り止めのない思い出が、あふれ出してきた。ぶどう畑でかくれんぼをしたことがある。負けた人がカバンを背負うゲームをしながら帰宅したことがある。自転車で一番早いのは誰か、坂道を登り切れるか、競争したことがある。キャベツ畑では、雨降りの中でてんとう虫を探した。雪が降った日には、凍りついた道路でスケートをした。雨が降ったり、風が吹いたり、いろいろなことが起きた。そういう、なんて事のない出来事が何百回も何千回も起きた。漫然とした、しかし輝かしい日常の舞台が、こんな風景を持っていた。そうしてやっと僕は理解した。これは僕らの街を描いた物語なのだ。

坂の上の狭すぎる家へ足を運んだ。床の畳がボロボロで、机だけで半分埋まってしまうような兄弟部屋。１４インチの小さなブラウン管テレビ。知っている。これが僕の家だ。張り付くように僕らはゲームをしていた。浴びるようにゲームをして、馬鹿みたいに遊んだ。たっぷり叱られて、電源を隠されたりもした。そんな少年たちの姿はここにはない。

断片的に思い浮かぶ全てのことが遠くて、懐かしくて、悲しい。真実はここにはない。ここは、昭和を切り取った博物館みたいに、嘘っぱちの模型だ。懐かしいねというために準備されたものでしかない。過去の残り滓にすぎない。本当を僕は知っている。この家はとっくの昔に取り壊されてしまったし、客のこない釣り堀は閉鎖された。葡萄畑は年月が経つほど狭くなり、荒れて行った。今では、怪物のように成長した雑草が争うように蔓を伸ばしていて立ち入ることは不可能になっている。

深いため息をつく。コントロールを失った主人公はただ立ち尽くしている。そうだ。僕はアルミのゲームをしているんだ。この街に、何かのイベントが仕込まれているはずだ。気を取り直して、街の中を回ってみることにした。街の中には目立たないように人影が配置されているだけで、それらは何一つ言葉を発することはなかった。探索範囲を広げて、ようやく一人の子供を見つけた。目立たない用水路の隅、僕らの秘密基地に彼女はいた。汚れたマットの上に寝そべって、携帯型のゲーム機に夢中になっている。

「今、いそがしいんだ。ここで百点を取らないと、本当のボスが出てこないから」

彼女が遊んでいたゲームは、ウサギのバニが登場する、一番最初のシリーズだった。僕は、このゲームを三周くらいはプレイしていたので、隠されたアイテムがどこにあるか知っていたし、難しい場面をどうやって切り抜ければ良いのか知っていた。彼女に助言してあげたいけれど、画面の中にそんな選択肢はない。

「そのゲーム、知ってるよ。でも本当のボスって、何？　XXXXが、ボスじゃないの？」

主人公が発言してようやく気がついた。僕が操作している彼は、子供だった。


* 4

畳張りの広い部屋だ。木製のテーブルの上に、２冊の薄い冊子が投げ出されていた。手書きの表紙には「修学旅行のしおり」と書かれている。すぐにピンときた。これは高校生の頃に行った、修学旅行の場面に違いない。

「早くしないと、死んじゃうよ」

笑い声がした。備え付けの大型テレビに、ゲーム画面が映っている。主人公は、少女に促されるままコントローラを握った。何かのミニゲームが始まった。見えにくい弾が飛んでくる。ああ、このゲームも知っている。僕はそう思った。しかし、画面の中の主人公は、そうでもないようだ。うまく操作できないままやられてしまった。

「ほら、死んだ」

また少女が笑った。主人公と少女は代わる代わるゲームをプレイしていたが、最初のボスまでたどり着くこともできなかった。理不尽な難しさを笑う。次こそはと意気込んでも、数分で死んでしまう。そんな呆気なさを笑う。乾いた笑いも出なくなった頃に彼女のなかで何かが切れたようだ。

「つまらん」

言うなり彼女はゲーム機を蹴っ飛ばして、最後にケーブルを引っこ抜いた。入力信号を失ったテレビは沈黙し、残された二人もまた沈黙した。主人公は転がったゲーム機を静かに片付ける。代わりに、大きな鞄の中から別のゲーム機を取り出した。コントローラは二つ。彼女は無言でそれを受け取る。対戦ゲームが始まった。二画面分割で、お互いシューティングをしながら勝負するという珍しいタイプのゲームだ。この作品も、僕は知っている。一度でも触れたら死んでしまう極端なゲームルールが、良くも悪くも個性的だった。

攻撃を避けてゲージを溜めながら、チャージショットで時間を稼いで、ボムを使って切り抜ける。基本の動きの繰り返しだ。このゲームは二人とも慣れているようだった。お互い、かすりもせずにスコアを伸ばしていく。長引く戦いに、だんだん興が乗ってきたようだ。死ねとか消えろとか物騒な言葉を発し、体を揺らしながら対戦している。

やがて、見回りの教員がやってきた。彼は二人がゲームに興じているのを見るなり一喝した。主人公は飛び上がるほど驚いて、コントローラを手放してしまった。その隙を逃さなかった少女が、見事に勝利を勝ち取った。教員は怒るよりも呆れて彼らに尋ねた。せっかく長い時間をかけて、新幹線まで使って旅行に来たというに、何故ゲームなんかで時間を浪費するのか、と。

「そうしたいからです」

教員は、端的な答えに納得しない。はぐらかされたと感じて、眉根を寄せた。

「先生は、何故わかりもしない質問をして時間を浪費するんですか？」

彼女の棘のある言葉に血が上った教員は、平手で頬を打った。

#+begin_comment
あの頃を思い出す。どうしようもなく楽しかった。少ないお小遣いを、効率よく使うために、安いショップを探して歩き回った。買ったゲームを貸し借りして、舐め尽くすように遊んだ。それは、枯れることのない井戸のように僕らを潤した。

修学旅行にだってゲームを持ち込んで、旅館に隠れ、夢中で遊んだ。そうして帰りの新幹線に乗り遅れて、しこたま怒られた。すべて、目が滲むほど懐かしい。その世界で、特別ゲームセンスのあったアルミは、僕らのヒーローだった。彼女に何度も挑んで、ボロボロに負けた毎日があった。悔しげにうめく僕らを、彼女は満足そうに見下ろしていた。何をやらせても上手いのは、それだけ練習しているということの証でもあった。初めは下手だった彼女があっという間に腕を上げてくるのは、僕らより前のめりだったからだろう。

ただ、一体どうしてこれほど破壊されてしまったのだろうか。壁は吹き飛ばされて、炭のようになっている。家財道具も見る影もない。妙に胸がざわついた。僕は、ゲームの中でアルミの家を探した。丘を超えたトンネルの先にある、二階建てのこぎれいな家。ゲームにどっぷりはまる前には、広い庭でキャッチボールをしたり、木登りをしたこともある。そんな爽やかな記憶に満ちた場所。

しかしそこには、全てを削りとったような深い深い穴があるだけだった。何か許すべからざるものを剥ぎ取ったような、そんな風にも見えた。これは架空の物語の一風景に過ぎないと言うのに、僕は暗い気持ちになった。

ポラリスはその大穴に興味を持ち、情報収集を始めた。しかし、街の人々はその場所に触れることを嫌がった。渋々語ることも抽象的でよくわからなかった。彼らが言うには、そこは、爆心地なのだと言う。汚れと、苦しみと、怒りと、理不尽と、不幸の始まりの場所なのだと言った。隔離して保存して置かねばならないのだと言った。

しつこく聞き込みを続けていると、警ら隊に拘束されてしまった。鋼のように無機質で強靭な男たちになすすべもなく連れ去られる。そしてポラリスは大穴に突き飛ばされてしまった。果てしない闇の中に吸い込まれていく。何か選択肢を誤っただろうか。落ちて砕けて、そこで、ゲームはおしまいなのかも知れない。考えるだけの時間がある。どこまでも落ちていく。不思議の国のアリスみたいだなと思った。終わりはやってこない。落ちていくポラリスのそばに、誰かがやってくる。その誰かも、自由落下に身を任せている。一人二人と数が増え、いつしか画面を埋め尽くすほどになった。

死の記録が流れ込んでくる。奈落に落ちた人それぞれの記録がこびりついていて、圧縮されたその様を逆再生しているのだという。殺されて、奪われて、その繰り返しだ。ここにいるのは敗者ばかりだ。奪われた者たちの記録だ。胸が悪くなるような場面ばかりが再生された。言葉だけで描かれたものに過ぎず、リアリティは感じられなかったが、人が貶められ、辱められ、奪われていく様を反復されるのは良いものではなかった。

そして、最後に再生されたのは、アルミという少女の記録だった。この街に生まれて、ゲームの世界に没入した少女の記録だった。

彼女は進学しなかった。どこへも行かないことを選んだ。社会の人との繋がりを失った彼女は、より空想にふけるようになった。社会不適合だと自虐しながら、いつまでもゲームに入り浸っていた。両親は初め、彼女を受け入れ、どうにか社会復帰させようとしていた。

しかし、どれだけ心を尽くしても、どれだけ時間を尽くしても彼女は全く変化しない。あらゆる愛情が素通りしてしまう。その絶望に絶えられず、父は壊れてしまった。

初めは酒に逃げて、家に寄り付かないようになる。愚痴をこぼす。まともな友人は呆れて離れていく。助け合うべき妻の心も離れていく。人間関係を失い、不安定になる。暴力を振るうようになる。日に日に悪化していくアルミの父と、全く変化のないアルミ。アルミの母は壊れていく家庭に耐えられなくなり、家を去る。家は荒んでいき、ゴミだらけになる。

そしてある日、すべてが決定的に壊れた。アルミの父は、アルミに暴力を振るい、そして彼女を陵辱した。社会の役に立たないなら、せめてこれぐらいはしろ。そう言ってゲラゲラ笑いながら、彼女を犯した。アルミは抵抗したが、吐くほど殴られて気絶させられた。

翌日、復讐に燃えた彼女は、家に火を放った。しかし、その試みはうまく行かなかった。優秀な消防隊によって、すぐさま消し止められてしまった。騒ぎを知った父は激怒し、彼女はより苛烈な暴力を浴びることになった。

アルミは火よりも深い憎しみと、怒りと呪いとを胸に抱いた。持て余した行き場のない狂気が、これまで愛してきたゲームという世界を投げ捨てさせた。彼女は代わりにスコップを手にとった。穴を掘る。合理的ではない。穴を掘って何かを解決しようとしているのではない。彼女は気が触れていた。ただ奈落へ、深淵への道を希求しているのであった。彼女は汗まみれになり、息を切らして喘ぎながら穴を掘った。貧弱な少女の力では、せいぜい人の半分ほどの深さにしかならなかった。

何日かけても、彼女は正気に戻らなかった。そして、狂気が濃くなるほどに穴は深く、不可視の悍ましいものが蓄積されていった。

彼女が完全に壊れるころ、それは完成した。闇色をしたマグマが噴き出し、全てを一瞬で覆い尽くしてしまった。彼女を蹂躙した父も、見向きもしなかった社会も全てを飲み込み、破壊し尽くした。ここで唐突に物語は終わってしまう。

セーブデータを遡って、何度繰り返しても同じ結末だった。他のエンディングはない。ネットでポーラスターを検索しても、全く別のページがヒットするばかりだった。そもそも、僕がこのゲームをダウンロードしたページさえも一般公開されていないらしく、このゲームの情報は一切見つからなかった。

僕はひどく動揺していた。ポーラスターのアルミは、現実のアルミではない。けれど、消息の知れないアルミがもし、同じ目に遭っていたとしたら。全てを噴火させたということは、命を絶ったということの暗示ではないか。憶測にすぎないが、彼女ならやりかねないと思った。

僕は何年もログインしていないSNSサービスをいくつか使って、彼女の名前を探した。しかし、足取りは一切つかめなかった。目の疲れを感じて、パソコンから離れる。ソファに身を任せて、目を瞑った。

僕が考えることをやめて機械的に働いていた間に、彼女は自分の生き方を貫こうとしていたのだろう。負けず嫌いだった彼女のことを思い出す。あんなに輝いていたのに。あんなに特別だったのに。ほんの少しでも僕が動いて、関わりを持っていたら、未来は変わっていただろうか。希望を与えることができただろうか。不安と悲しみと後悔で胸がいっぱいになった。

# 家庭が壊れ、実父に襲われたとき、どれほどの絶望を抱えていただろう。そんな中で記録のためにポーラスターを作り上げた執念を想像する。あれだけのボリュームだ。一朝一夕に作れるとは思えない。少なくとも一ヶ月はかかったのではないだろうか。無我夢中で作っていただろう。それに彼女が満足したなら、作り上げてからどうなったのかは、どこにも描かれていない。
#+end_comment
