* 1

ポラリス。揺るぎない不動の座。はるか北の地で生まれた少年に、その名は与えられた。彼は、森の中に住み猟師を生業とする貧しい家に生まれた。遠い系譜を辿れば、彼の一族は権力者として国を支配したこともある。しかし、国を追われて何世代も経た今では、それも霞と消えてしまった。ポラリスの母は、産褥熱のために命を落とした。

ポラリスは父に習って、獣たちを撃つすべを学んだ。仕留めた獲物はナイフを使って皮を剥ぎ、骨を外し、肉を切り分ける。寡黙な父はいつも仕事にポラリスを連れていき、狩りの手法を教えた。獣たちの鳴き声や習性、足跡の追い方、縄張りやフンの見分け方、急所について。ポラリスの眼前で、獣たちの命が明滅していく。ついさっきまで、生き生きと躍動していた獣が、撃たれ、もがき、虚な目で死んでいく。それは彼にある種の諦観を植え付けた。人もまた獣であり、いつかそのような死を迎えるのだろう。彼は、漠然とそう考えていた。

時にはいくらかの人が訪れ、そして去っていく。行商人と、ありものを交換する。それは、あまりにささやかなものだ。鹿の毛皮や角を手放して、陶器のカップを手に入れたり、使えない猟犬をそばに置いたりするだけだ。作物の育たないこの地域では、総生産は非常に低い。まともな医療もない。だから、彼が大人になるだけの時間が流れても、ほとんど集落の人口は変わらなかった。

父は母の命日が近づくたびに、端材を使って鳥の置物を作った。手のひらに収まるほどの小ぶりのものだ。生前の母は、その鳥が好きだったのだという。年が過ぎるたび、窓際に並ぶ鳥たちが増えていくのだった。ポラリスもそれを真似て、毎年一つ、不恰好な鳥を作るようになっていた。

ポラリスが一人で狩りに出ることを認められた頃、凶暴な鬼が集団で村を襲っているという噂が流れ始めた。それは、人の形を成してはいるものの肌は青く、意思疎通は不可能であり、破壊のかぎりを尽くすのだという。すでに、魔物に滅ぼされた集落が無数にあるらしい。村の男たちは協力して集落の要塞化を試みることになった。

しかし悲劇は訪れた。ポラリスたちがどれだけ集落を堅固にしたところで、鬼たちはそれを意に介さなかった。彼らの武器は粗末な棍棒であったが、肥大した筋肉から振るわれるそれは、明らかに人類のいかなる武器よりも強力であった。どんな罠も、ものともせず根こそぎ破壊し、土塁を吹き飛ばした。抵抗したものは、次の瞬間に首のない死体となって転がっている。父は果敢に立ち向かい、銃を使って数匹の鬼を仕留めたが、それまでだった。怒りを買った父は骨も残らないほど粉砕されてしまった。残された血溜まりに、ポラリスは震え上がり、立ち上がることもできなくなった。

備えを突破された集落は、あまりにも脆かった。屍が山を成し、残されたものたちは捕らえられた。獣たちの命を容易く奪ってきた自分達が、鬼に蹂躙されるのは自然の摂理なのだろう。ポラリスは死を覚悟した。

しかし、ポラリスを待っていたのは死ではなく過酷な肉体労働だった。鬼たちは王によって統率されており、言語を持ち、文明を築いていた。王は自らの都を作るための労働力を求めていた。ポラリスは四六時中の間、土木作業を強制された。鬼たちの圧倒的暴力を目の当たりにして以来、彼は抵抗するのをやめていた。ただ従順に使い潰されていった。

やがて、母の命日が近づいてきた。彼は記憶の片隅から、鳥の置物のことを思い出した。ポラリスはわずかな休憩時間を縫って、寝る間を惜しんで工作に没頭した。やり場のない感情をぶつけていたのかもしれない。月が満ち、欠けて消え、また満ちる頃、ようやくそれは完成した。これまでに彼が作ったどの置物よりも研ぎ澄まされていた。石で削り、砂で磨いた面は滑らかで、触ると温かみが感じられるような気がした。彼は満足気に頷くと、ばたりと意識を失った。

鬼の子供たちが騒いでいる。倒れたポラリスを見物にやって来たのだ。度重なる重労働と睡眠不足、栄養不足によって、ポラリスは虫の息だった。大人の鬼がやってくる。彼はポラリスをつまみあげ、骨塚に捨て去った。しかし、すぐさま女の鬼が歩み寄ってきた。他の鬼と一線を画した金の刺繍から王族のそれとわかる。彼女はポラリスを軽々と持ち上げ、子供を抱くように、小脇に抱えて連れ去っていった。空いた方の手にはポラリスの鳥を優しく握っている。

#+begin_comment
時には、助けを求めるものがいる。そこで与えられる選択肢は、助けるか助けないかという単純な二択だ。僕はゲームをリセットしながら、二つの選択肢のどちらも試してみたが、どちらを選んだとしてもあまり意味はなかった。それは遭難者に見せかけた野盗であったり、集落を支配しようとする侵略者であったりした。気の狂った犯罪者もいた。ともかく、誰も彼も、ろくでもない訪問者ばかりだった。同じ集落の仲間でさえも、貧しさや嫉妬からポラリスに牙を剥いた。ポラリスの家は簡素なものだし、彼が襲われる言われはないのだが、それでも人々は、彼から奪い取ろうとするのだった。僕はポラリスを操作して、それらに対峙した。

アルミが作っただけあって、適当に操作していたらあっという間にゲームオーバーになるような難易度に設定されている。でも、その手応えが心地良い。僕は腰を据えてこのゲームに取り組んでいたので、長く足止めを食らうことはなかった。

ゲームの中で一年の月日が流れた。集落の男が大慌てでやってくる。勇者が魔王を討ったのだという。彼は大喜びしていたが、ポラリスは無感動なまま立ち尽くしていた。実際、彼の身の回りは全く変化がなかった。野盗は減らないし、魔物が迷い込んでくるのも変わらない。その暮らしの中に彼はあって、それ以外の出来事は遠い世界のままでしかなかった。魔王が消えた世界では、共通の敵を失った人間たちの戦争が始まった。奪い奪われる戦い。戦火は広がり、そしてそこから逃れようとする者たちが北へ北へとやってくる。

ポラリスたちのいる集落にも、故郷を失った難民が訪れた。難民を追い払うか、迎え入れるかの選択肢が現れた。僕は素直に難民を受け入れることを選んだ。その結果、難民たちは食料を食い潰し、それに怒った友人を殺して、財産を奪い去っていった。代わり映えのしなかったマップが血で染まり、路傍には打ち捨てられた死体が転がっていた。唯一の家族、使えない猟犬も、蹴られて死んでいた。ポラリスは、一人取り残された。僕はひどく動揺してリセットした。

僕は集落が滅びるのを避けるために、難民たちを拒絶した。難民たちは怒り、特に荒くれ者たちは襲いかかってきた。彼らは決して強者ではなかった。遠く逃げ落ちる旅の中で体力を失っていたのだろう。あっけなく倒れた。戦えない老人や女子供は逃げ惑い、姿を消した。数日と経たないうちに、雪の中に埋もれた死体が大量に見つかった。僕は修羅だ非人間だと唾を吐きかけられ、石を投げられた。もはや村で生きていくことはできなかった。

いずれも正解ではなかった。背後にいるアルミが、いかなる選択も、世界に影響を及ぼすことはできないのだと語っている気がした。

ポラリスは旅に出た。彼は、これまで遠くへ行った経験がなかったから、文字通り世間知らずだった。言葉も、文化も、ものの価値も知らない。馬鹿にされたり、騙されたりする。それでも、少しずつ変化していく。旅仲間に、猟犬を失ったことを話す。名前は何だったのかと問われる。名前はなかったと答える。墓を作ることもできないな、と静かに憐れみを受ける。それ以上、物語られることはない。善も悪も語らないその世界観が、僕には心地良く感じられた。

学んだり失ったりしながら、荷物も仲間も増えないまま、流れに流れて、聖地と呼ばれる土地にやってきた。それがいかなる理由でそう呼ばれているのかはわからない。そこに信仰はない。宗教的意義もない。豊かではなく、文化的ではなく、平和でもなかった。物々しく隔離区域と書かれた看板がある。ポラリスはその領域に足を踏み入れた。
#+end_comment
