* 1

朝6時に目を覚まし、電車に乗り込んだ。みんな、まだ眠そうにしている。今日の講義を確認した。朝から英作文、解析数学、離散数学と続いて、最後に物理学基礎実験が二枠ある。空いた座席に腰掛けて、教科書をパラパラとめくってみた。数学に関しては高校数学の延長なので特に問題はなさそうだけれど、英作文に関しては全く自信がなかった。教科書を眺めているうちに、やっぱり居眠りしてしまった。

最寄りの駅で降りて、講義棟へ直接向かうバスに乗り込んだ。同級生たちが楽しげに会話しているのが目に入った。最初に友達を作るチャンスを逃してしまってから、どうも輪に入れないままでいる。

僕は、なるべく目立たないように一番奥の端に座って、窓の外を見ていた。桜は散ってしまったけれど明るい緑がきれいだ。いくつもある運動場を通り過ぎて、終点に到着した。英作文のクラスで、外国人教師の講義を受けた。そのまま無難に数学の講義を終えて、昼休みになった。

教室を出て、ふらふらと大学構内を歩く。食堂から遠く離れた、研究棟の裏のベンチに腰掛けた。一人で食事をするのがどうも気恥ずかしくて、目立たないところに逃げてしまう。ここなら、ほとんど人がいないし、研究棟が影になっていて過ごしやすい。

母が持たせてくれた弁当箱を開けた。冷凍食品のハンバーグを口に放り込んだ。つまらない味だけれど、悪くない。大学生にもなって、こんなふうに弁当を作ってもらっていいのだろうか。大学の中には学生生協という名前のコンビニみたいな施設が入っているので、弁当くらいなら買うこともできる。それでも、朝6時半に家を出る僕のためにせっせと弁当を準備している母を止めることはできなかった。やつれ顔の男が、タバコを咥えてやってくる。僕は慌てて弁当を片付けて、席を立った。

夕方の講義も滞りなく終え、最後の枠で実験が始まった。まず、クラス全員が集められて実験の手順が説明された。学生たちはグループに別れ、つる巻きばねにおもりをつけ、伸びたバネの長さを測る。これをグラフに書き込んで、考察をレポートすれば終わりだ。

クラスメイトの一人が隣に座った。彼女の名前は新谷玖。女性としてはかなり大柄で、同級生と比べると、文字通り頭ひとつ出ている。いつもジャージみたいな服装をしている。髪も短いので、動きやすそうなスタイルが好きなのかもしれない。目立つ人だから、なんとなく覚えていた。他のメンバーとも軽く挨拶して実験を始めた。
